version: 0.0
os: linux

hooks:
   BeforeInstall:
    - location: scripts/start.sh
      runas: root
   Install:
    - location: scripts/start.sh
      runas: root
   AfterInstall:
    - location: scripts/restart.sh
      runas: root
